services:
  krtbanking-api:
    image: krtbanking-api
    build:
      context: .
      dockerfile: src/KRTBanking.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
