services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: krtbanking-dynamodb-local
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - krtbanking-network

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: krtbanking-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    networks:
      - krtbanking-network

  krtbanking-api:
    image: krtbanking-api
    build:
      context: .
      dockerfile: src/KRTBanking.API/Dockerfile
    container_name: krtbanking-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - AwsConfig__ServiceURL=http://dynamodb-local:8000
      - AwsConfig__AccessKey=fakeMyKeyId
      - AwsConfig__SecretKey=fakeSecretAccessKey
    depends_on:
      - dynamodb-local
    networks:
      - krtbanking-network

networks:
  krtbanking-network:
    driver: bridge
