# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "C:\\Users\\gio\\Documents\\dev\\KRTBanking"
      dockerfile: "src/KRTBanking.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/KRTBanking.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "api:dev"
    ports: []
    volumes:
    - "C:\\Users\\gio\\Documents\\dev\\KRTBanking\\src\\KRTBanking.API:/app:rw"
    - "C:\\Users\\gio\\Documents\\dev\\KRTBanking:/src:rw"
    - "C:\\Users\\gio\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
